### ISSUE TITLE
circular dep between create_description and turtlebot_description

### ISSUE THREAD

**Issue by mmwise** [turtlebot/turtlebot_create#1]
the meshes for the create need to be moved into the create_description to make this go away.

https://github.com/turtlebot/turtlebot/blob/master/turtlebot_description/urdf/turtlebot_library.urdf.xacro
https://github.com/turtlebot/turtlebot_create/blob/master/create_description/urdf/create.urdf.xacro

**Comment by stonier** [comment]
This seems like it is ok? Please reopen if necessary.
