### ISSUE TITLE
cannot connect on indigo

### ISSUE THREAD

**Issue by vliedel** [turtlebot/turtlebot_create#16]
Hi I'm having trouble connecting to a roomba 521 on ros indigo. I have a laptop running hydro, where it connects just fine and a laptop running indigo, where I installed many nodes from source (using catkin).
On indigo I get the error "Failed to open port ....". I checked the dev rules, dmesg, ls -l /dev/ttyUSB0 and also tried to connect with minicom, to which it responds with a beep when I exit&reset (just like on the hydro laptop).
I have these environmental vars:
TURTLEBOT_BASE roomba
TURTLEBOT_STACKS circles
TURTLEBOT_SERIAL_PORT /dev/ttyUSB0

I'm wondering if there's any difference of connecting between hydro and indigo.

**Comment by PaulBouchier** [comment]
vliedel,
Edit <path_to_turtlebot_source>/turtlebot_create/create_node/nodes/turtlebot_node.py, and change the line (approx line 128) that says "msg = "Failed to open port...." to the following:

msg = "Failed to open port %s, Error: %s Please make sure the Create cable is plugged into the computer. \n"%((self.port), ex.message)

Save the file and launch the minimal.launch. Report the exact error message, which will now contain enough information to know the exact error. We can go from there.

**Comment by vliedel** [comment]
Hey, thanks for the quick reply :)
Here's the error message I got:

[ERROR] [WallTime: 1406030305.159096] Failed to open port /dev/ttyUSB0. Error: Port is already open. Please make sure the Create cable is plugged into the computer.

This is next to some rocon_app_manager errors, which i ignored for now.

And just to be sure I added some extra info about the device:
$ dmesg | grep tty
[    0.000000] console [tty0] enabled
[  274.003694] usb 3-2: FTDI USB Serial Device converter now attached to ttyUSB0
$ ls -l /dev/ttyUSB0 
crw-rw-rw- 1 root dialout 188, 0 jul 22 13:57 /dev/ttyUSB0
$ grep dialout /etc/group
dialout: x:20:vliedel

**Comment by PaulBouchier** [comment]
This is issue #17 
Here's a workaround until Daniel & his merry band update their repo. Edit the following file:
turtlebot/src/turtlebot_create/create_driver/src/create_driver/create_driver.py
Around line 213 you'll find two lines:
self.ser = serial.Serial(tty, baudrate=baudrate, timeout=SERIAL_TIMEOUT)
self.ser.open()

Delete the second line - it's trying to open the serial port a second time.

This should enable turtlebot_teleop keyboard_teleop.launch to work.

**Comment by kentsommer** [comment]
@PaulBouchier @vliedel 

The fix for this (thanks @PaulBouchier) has been merged into the repo. See #18 

:bowtie:

**Comment by jlzizmor** [comment]
i'm having the same issue, however I checked the turtlebot dir and I don't have any further directories, just a package.xml.

I started installing all the software for the turtlebot and the steps instructed me to launch minimal.launch. Did I miss a step to fill out the turtlebot directory?

**Comment by trainman419** [comment]
@jlzizmor if you installed from binaries, this bug should be fixed in the version that you have.

If you installed from source, you would have the source, but this bug should still be fixed.

I suspect your problem isn't related to this; rather you probably don't have the permissions on your serial port set correctly.

**Comment by lucbettaieb** [comment]
Wait a sec- does turtlebot_create work on more than just the iRobot create 1?

I was planning on writing drivers eventually for the create 2 but was looking at a bunch of the serial commands and they seemed to be the same.

Any idea on how to run the drivers to get them working with indigo+create 2?
