### ISSUE TITLE
Cannot load create.urdf.xacro in ROS jade

### ISSUE THREAD

**Issue by dcconner** [turtlebot/turtlebot_create#29]
I'm trying to use the create package under ROS Jade.
'
 rosrun xacro xacro --inorder --verbosity=4  create.urdf.xacro
set base_x: 0.33 (create.urdf.xacro)
set base_y: 0.33 (create.urdf.xacro)
<?xml version="1.0" ?>
< ! - - =================================================================================== - ->
< ! - - |    This document was autogenerated by xacro from create.urdf.xacro              | - - >
< !  -- |    EDITING THIS FILE BY HAND IS NOT RECOMMENDED                                 | - - >
<  ! - - ===================================================================================  - - >

< robot name="turtlebot_hardware" xmlns:xacro="http://ros.org/wiki/xacro" >
< / robot >

'
and nothing else.  I cannot load the description into Gazebo.
I have the turtlebot_create  turtlebot_create_desktop packages checked out and built in my catkin_ws

**Comment by skohlbr** [comment]
The create.urdf.xacro file just contains a macro for instantiating a create model, but does not call it. The intended use is to include the create.urdf.xacro file in your model and then instantiate it like so:

```
<xacro:include filename="$(find create_description)/urdf/create.urdf.xacro"/>
<create />
```

The macro is used in the Turtlebot setup if the appropiate environment variables are set for instance from here: https://github.com/turtlebot/turtlebot/blob/indigo/turtlebot_description/robots/create_circles_kinect.urdf.xacro

**Comment by dcconner** [comment]
Thanks.  Now my issue is the plugin isn't finding 
[ERROR] [1453505874.317392841, 0.330000000]: Unable to find geom [base_footprint_collision_base_link]

But that is another issue.  The reduced model is loading for me.
